# Generated by Django 5.0.6 on 2024-07-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0027_remove_staffdepartment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetails',
            name='password',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
