# Generated by Django 5.0.6 on 2024-08-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0027_remove_staffdepartment_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='default_table',
        ),
        migrations.DeleteModel(
            name='StaffDepartment',
        ),
        migrations.RemoveField(
            model_name='leave_availability',
            name='initial_casual_remaining',
        ),
        migrations.RemoveField(
            model_name='leave_availability',
            name='initial_ch_leave_remaining',
        ),
        migrations.RemoveField(
            model_name='leave_availability',
            name='initial_earn_leave_remaining',
        ),
        migrations.RemoveField(
            model_name='leave_availability',
            name='initial_medical_leave_remaining',
        ),
        migrations.RemoveField(
            model_name='leave_availability',
            name='initial_onduty_remaining',
        ),
        migrations.RemoveField(
            model_name='leave_availability',
            name='initial_vaccation_remaining',
        ),
        migrations.RemoveField(
            model_name='staffdetails',
            name='is_principal',
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='password',
            field=models.CharField(default='srec@123', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='department',
            field=models.CharField(choices=[('ECE', 'ECE'), ('CSE', 'CSE'), ('EIE', 'EIE'), ('MATHS', 'MATHS'), ('CHEMISTRY', 'CHEMISTRY'), ('ENGLISH', 'ENGLISH'), ('PHYSICS', 'PHYSICS'), ('RAE', 'RAE'), ('MECH', 'MECH'), ('EEE', 'EEE'), ('BME', 'BME'), ('AERO', 'AERO'), ('CIVIL', 'CIVIL'), ('IT', 'IT'), ('NANO', 'NANO'), ('AIDS', 'AIDS'), ('MBA', 'MBA'), ('NT', 'NT')], max_length=100),
        ),
    ]
