# Generated by Django 5.0.6 on 2024-08-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0028_delete_default_table_delete_staffdepartment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='default_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual_leave_default', models.IntegerField(default=12)),
                ('LOP_leave_default', models.IntegerField(default=0)),
                ('CH_leave_default', models.IntegerField(default=0)),
                ('medicalLeave_default', models.IntegerField(default=5)),
                ('earnLeave_default', models.IntegerField(default=5)),
                ('vaccationLeave_default', models.IntegerField(default=15)),
                ('specialOnduty_default', models.IntegerField(default=0)),
                ('onDuty_default', models.IntegerField(default=14)),
            ],
        ),
        migrations.CreateModel(
            name='FrozenDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departments', models.JSONField(default=list)),
            ],
        ),
        migrations.AddField(
            model_name='leave_availability',
            name='initial_casual_remaining',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='leave_availability',
            name='initial_ch_leave_remaining',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='leave_availability',
            name='initial_earn_leave_remaining',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='leave_availability',
            name='initial_medical_leave_remaining',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='leave_availability',
            name='initial_onduty_remaining',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='leave_availability',
            name='initial_vaccation_remaining',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lop_leave',
            name='document',
            field=models.FileField(upload_to='leave_documents/'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='password',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
